name: 'Manifesting Joy!'
favicon: null
layout_spectrum: 0.31198365334421396
typography_spectrum: 0.2262966411653906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05562140000984073
  lightness: 0.8599644128698856
  saturation: 0.0009589020628482103
  rhythmicContrast: 0.29378723446279764
purpose: []
